services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - kafka-net
    environment:
      KAFKA_NODE_ID: 1 # KRaft를 사용할 때 필요하다. 노드ID는 각 노드의 식별자
      KAFKA_PROCESS_ROLES: "broker,controller" # zookeeper를 사용하지 않고 KRaft를 사용
      KAFKA_LISTENERS: "CONTROLLER://:9093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092" # 컨트롤러, 외부접속, 내부 브로커끼리 통신 포트 설정
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092" # 외부에서 브로커에 접속할때 접근할 주소.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093" # zookeeper.connect와 대응하는 역할.
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER" # KRaft를 사용할 때 필요함.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.8.0
    container_name: kafka-connect
    ports:
      - "8083:8083"
    networks:
      - kafka-net
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:19092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/kafka-connect,/data/connect-jars
    volumes:
      - ./kafka-connect/connector/confluentinc-kafka-connect-jdbc/lib:/usr/share/kafka-connect
      - ./kafka-connect/mysql:/etc/kafka-connect/jars
networks:
  kafka-net:
    driver: bridge
