services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "4369:4369"
      - "5671:5671"
      - "15671:15671"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest	
    networks: 
      - ecommerce-network
    
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: config-service
    ports:
      - "8888:8888"
    # environment:
    #   SPRING_RABBITMQ_HOST: rabbitmq
    #   SPRING_PROFILES_ACTIVE: default
    #   ENCRYPT_KEY-STORE_LOCATION: file:/apiEncryptionKey.jks
    networks:
      - ecommerce-network

  discovery-service:
    build:
      context: ./discoveryservice
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8761:8761"
    # environment:
    #   SPRING_CLOUD_CONFIG_NAME: ecommerce
    #   SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge