services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - "--web.enable-lifecycle"
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus/config:/etc/prometheus
    networks:
      - monitor-net
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge