server:
  port: 0 #랜덤 포트 할당

spring:
  application:
    name: user-service
#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  cloud:
    config:
      name: user-service # yml file name
#      profile: dev
  config:
    import: optional:configserver:http://127.0.0.1:8888


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true  # eureka 서버에 등록
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    org.springframework.security: debug
    com.example.userservice.client: debug
    com.example.userservice: debug
  pattern:
    correlation: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  # actuator config
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus

#token:
#  expiration-time: 86400000 # 1day
#  secret: ZGG1}v0m:t.U}wvN]r#)Y_.:c}Ydm8p*