server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
#    host: 127.0.0.1
    host: rabbitmq # 같은네트워크에 있는 경우 container 이름으로 접근 가능
    port: 5672
    username: guest
    password: guest
#  profiles:
#      active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/Desktop/config-local-repo
        git:
#          uri: file:///C:\Users\gusej\Desktop\config-data
          uri: https://github.com/gusejr4547/toypj-msa-config
          default-label: master
#          username: <github-id>
#          password: <github-accessToken>
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

encrypt:
#  key: abcdefghijklmnopqrstuvwxyz0123456789
  key-store:
#    location: file:///${user.home}/Desktop/keystore/apiEncryptionKey.jks # privateKey
    location: file:/apiEncryptionKey.jks
    password: test1234
    alias: apiEncryptionKey